baseURL = 'https://freeebies.site'
languageCode = 'en-us'
title = 'Freebies'
github="steveyout"

[module]
# uncomment line below for temporary local development of module
# or when using a 'theme' as a git submodule
replacements = "github.com/steveyout/lotusdocs -> lotusdocs"
[[module.imports]]
path = "github.com/steveyout/lotusdocs"
disable = false
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/bootstrap'
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/font-awesome'

[params]

google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
]

sans_serif_font = "Inter"     # Default is System font
secondary_font  = "Inter"     # Default is System font
mono_font       = "Fira Code" # Default is System font

[markup.goldmark.renderer]
unsafe = true

[params.footer]
copyright = "© :YEAR: Freebies. Built with ❤ by [**Steveyout**](https://github.com/steveyout)"
# version = true # includes git commit info

[params.social]
github = "steveyout/Freebies"        # YOUR_GITHUB_ID or YOUR_GITHUB_URL
#twitter = ""       # YOUR_TWITTER_ID
# instagram = "colinwilson"     # YOUR_INSTAGRAM_ID
# rss = true                    # show rss icon with link

[params.docs] # Parameters for the /docs 'template'
title           = "Freebies - a collection of free stuff on the internet"           # default html title for documentation pages/sections

# pathName        = "docs"                            # path name for documentation site | default "docs"

# themeColor      = "red"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan

darkMode        = true                                # enable dark mode option? default false

prism           = true                                # enable syntax highlighting via Prism

prismTheme      = "solarized-light"                           # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

# gitinfo
repoURL         = "https://github.com/steveyout/Freebies"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
repoBranch      = "release"
editPage        = true                                # enable 'Edit this page' feature - default false
lastMod         = true                                # enable 'Last modified' date on pages - default false
lastModRelative = true                                # format 'Last modified' time as relative - default true

sidebarIcons    = true                                # enable sidebar icons? default false
breadcrumbs     = true                                # default is true
backToTop       = true                                # enable back-to-top button? default true

# ToC
toc             = true                                # enable table of contents? default is true
tocMobile       = true                                # enable table of contents in mobile view? default is true
scrollSpy       = true                                # enable scrollspy on ToC? default is true

# front matter
descriptions    = true                                # enable front matter descriptions under content title?
titleIcon       = true                                # enable front matter icon title prefix? default is false

# content navigation
navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description

# Link behaviour
intLinkTooltip  = true                                # Enable a tooltip for internal links that displays info about the destination? default false
# extLinkNewTab   = false                             # Open external links in a new Tab? default true
# logoLinkURL = ""                                    # Set a custom URL destination for the top header logo link.

[params.flexsearch] # Parameters for FlexSearch
  enabled             = true
  tokenize            = "full"
  optimize            = true
  cache               = 100
# minQueryChar        = 3 # default is 0 (disabled)
# maxResult           = 5 # default is 5
# searchSectionsIndex = []

[params.docsearch] # Parameters for DocSearch
 appID     = "RK6EU786CJ" # Algolia Application ID
 apiKey    = "7e2c0954b95bc99c95f021fc457be28e" # Algolia Search-Only API (Public) Key
 indexName = "freeebies" # Index Name to perform search on (or set env variable HUGO_PARAM_DOCSEARCH_indexName)

[params.analytics] # Parameters for Analytics (Google, Plausible)
# plausibleURL    = "/docs/s" # (or set via env variable HUGO_PARAM_ANALYTICS_plausibleURL)
# plausibleAPI    = "/docs/s" # optional - (or set via env variable HUGO_PARAM_ANALYTICS_plausibleAPI)
# plausibleDomain = ""      # (or set via env variable HUGO_PARAM_ANALYTICS_plausibleDomain)
[services]
  [services.googleAnalytics]
    id = 'G-HHK1B8QGWH'


[params.feedback]
     enabled = true
     emoticonTpl = true
     eventDest = ["google"]
     emoticonEventName = "Feedback"
     positiveEventName = "Positive Feedback"
     negativeEventName = "Negative Feedback"
     positiveFormTitle = "What did you like?"
     negativeFormTitle = "What went wrong?"
     successMsg = "Thank you for helping to improve Freebies documentation!"
     errorMsg = "Sorry! There was an error while attempting to submit your feedback!"
     positiveForm = [
       ["Accurate", "Accurately describes the feature or option."],
       ["Solved my problem", "Helped me resolve an issue."],
       ["Easy to understand", "Easy to follow and comprehend."],
       ["Something else"]
     ]
     negativeForm = [
       ["Inaccurate", "Doesn't accurately describe the feature or option."],
       ["Couldn't find what I was looking for", "Missing important information."],
       ["Hard to understand", "Too complicated or unclear."],
       ["Code sample errors", "One or more code samples are incorrect."],
       ["Something else"]
     ]

[[menu.primary]]
    name  = "Home"
    url = "/docs/"
    identifier = "home"
    weight = 10

[[menu.primary]]
     name  = "Contribute"
     url = "https://github.com/steveyout/Freebies"
     identifier = "contribute"
     weight = 20

[[menu.primary]]
     name  = "Community"
     url = "https://discord.gg/V85c4wvB5a"
     identifier = "community"
     weight = 30
